import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Sections/Footer";
import Nav from "./components/Sections/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jenna Ly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative max-w-screen-xl mx-auto pb-10`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
